In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv('/content/Loan_default.csv')
df.head()

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,...,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default,Loan Date (DD/MM/YYYY),Predicted_Default,Default_Probability
0,I38PQUQS96,56,85994,50587,520,80,4,15.23,36,0.44,...,Full-time,Divorced,Yes,Yes,Other,Yes,0,10/15/2018,0,0.183086
1,HPSK72WA7R,69,50432,124440,458,15,1,4.81,60,0.68,...,Full-time,Married,No,No,Other,Yes,0,3/25/2016,0,0.171012
2,C1OZ6DPJ8Y,46,84208,129188,451,26,3,21.17,24,0.31,...,Unemployed,Divorced,Yes,Yes,Auto,No,1,11/11/2013,1,0.657567
3,V2KKSFM3UN,32,31713,44799,743,0,3,7.07,24,0.23,...,Full-time,Married,No,No,Business,No,0,6/22/2017,1,0.588414
4,EY08JDHTZP,60,20437,9139,633,8,4,6.51,48,0.73,...,Unemployed,Divorced,No,Yes,Auto,No,0,6/9/2014,0,0.419967

In [ ]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 255347 entries, 0 to 255346
Data columns (total 21 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   LoanID                  255347 non-null  object
 1   Age                     255347 non-null  int64
 2   Income                  255347 non-null  int64
 3   LoanAmount              255347 non-null  int64
 4   CreditScore             255347 non-null  int64
 5   MonthsEmployed          255347 non-null  int64
 6   NumCreditLines          255347 non-null  int64
 7   InterestRate            255347 non-null  float64
 8   LoanTerm                255347 non-null  int64
 9   DTIRatio                255347 non-null  float64
 10  Education               255347 non-null  object
 11  EmploymentType          255347 non-null  object
 12  MaritalStatus           255347 non-null  object
 13  HasMortgage             255347 non-null  object
 14  HasDependents           255347 non-null  object
 15  LoanPurpose             255347 non-null  object
 16  HasCoSigner             255347 non-null  object
 17  Default                 255347 non-null  int64
 18  Loan Date (DD/MM/YYYY)  255347 non-null  object
 19  Predicted_Default       255347 non-null  int64
 20  Default_Probability     255347 non-null  float64
dtypes: float64(3), int64(9), object(9)
memory usage: 40.9+ MB

LoanID                    0
Age                       0
Income                    0
LoanAmount                0
CreditScore               0
MonthsEmployed            0
NumCreditLines            0
InterestRate              0
LoanTerm                  0
DTIRatio                  0
Education                 0
EmploymentType            0
MaritalStatus             0
HasMortgage               0
HasDependents             0
LoanPurpose               0
HasCoSigner               0
Default                   0
Loan Date (DD/MM/YYYY)    0
Predicted_Default         0
Default_Probability       0
dtype: int64

In [ ]:
loan_ids = df["LoanID"]
df_model = df.drop(columns=["LoanID", "Loan Date (DD/MM/YYYY)"])
df_model["Loan_to_Income"] = df_model["LoanAmount"] / df_model["Income"]
df_model["Credit_per_Year_Employed"] = df_model["CreditScore"] / (df_model["MonthsEmployed"] + 1)

categorical_cols = ["Education", "EmploymentType", "MaritalStatus",
                     "HasMortgage", "HasDependents", "LoanPurpose", "HasCoSigner"]

df_encoded = pd.get_dummies(df_model, columns=categorical_cols, drop_first=True)

print(df_encoded.shape)
print(df_encoded.columns.tolist())

(255347, 29)
['Age', 'Income', 'LoanAmount', 'CreditScore', 'MonthsEmployed', 'NumCreditLines', 'InterestRate', 'LoanTerm', 'DTIRatio', 'Default', 'Predicted_Default', 'Default_Probability', 'Loan_to_Income', 'Credit_per_Year_Employed', 'Education_High School', "Education_Master's", 'Education_PhD', 'EmploymentType_Part-time', 'EmploymentType_Self-employed', 'EmploymentType_Unemployed', 'MaritalStatus_Married', 'MaritalStatus_Single', 'HasMortgage_Yes', 'HasDependents_Yes', 'LoanPurpose_Business', 'LoanPurpose_Education', 'LoanPurpose_Home', 'LoanPurpose_Other', 'HasCoSigner_Yes']

In [ ]:
df_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 255347 entries, 0 to 255346
Data columns (total 29 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Age                           255347 non-null  int64
 1   Income                        255347 non-null  int64
 2   LoanAmount                    255347 non-null  int64
 3   CreditScore                   255347 non-null  int64
 4   MonthsEmployed                255347 non-null  int64
 5   NumCreditLines                255347 non-null  int64
 6   InterestRate                  255347 non-null  float64
 7   LoanTerm                      255347 non-null  int64
 8   DTIRatio                      255347 non-null  float64
 9   Default                       255347 non-null  int64
 10  Predicted_Default             255347 non-null  int64
 11  Default_Probability           255347 non-null  float64
 12  Loan_to_Income                255347 non-null  float64
 13  Credit_per_Year_Employed      255347 non-null  float64
 14  Education_High School         255347 non-null  bool
 15  Education_Master's            255347 non-null  bool
 16  Education_PhD                 255347 non-null  bool
 17  EmploymentType_Part-time      255347 non-null  bool
 18  EmploymentType_Self-employed  255347 non-null  bool
 19  EmploymentType_Unemployed     255347 non-null  bool
 20  MaritalStatus_Married         255347 non-null  bool
 21  MaritalStatus_Single          255347 non-null  bool
 22  HasMortgage_Yes               255347 non-null  bool
 23  HasDependents_Yes             255347 non-null  bool
 24  LoanPurpose_Business          255347 non-null  bool
 25  LoanPurpose_Education         255347 non-null  bool
 26  LoanPurpose_Home              255347 non-null  bool
 27  LoanPurpose_Other             255347 non-null  bool
 28  HasCoSigner_Yes               255347 non-null  bool
dtypes: bool(15), float64(5), int64(9)
memory usage: 30.9 MB

In [ ]:
bool_cols = df_encoded.select_dtypes(include='bool').columns
df_encoded[bool_cols] = df_encoded[bool_cols].astype(int)

In [ ]:
df_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 255347 entries, 0 to 255346
Data columns (total 29 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Age                           255347 non-null  int64
 1   Income                        255347 non-null  int64
 2   LoanAmount                    255347 non-null  int64
 3   CreditScore                   255347 non-null  int64
 4   MonthsEmployed                255347 non-null  int64
 5   NumCreditLines                255347 non-null  int64
 6   InterestRate                  255347 non-null  float64
 7   LoanTerm                      255347 non-null  int64
 8   DTIRatio                      255347 non-null  float64
 9   Default                       255347 non-null  int64
 10  Predicted_Default             255347 non-null  int64
 11  Default_Probability           255347 non-null  float64
 12  Loan_to_Income                255347 non-null  float64
 13  Credit_per_Year_Employed      255347 non-null  float64
 14  Education_High School         255347 non-null  int64
 15  Education_Master's            255347 non-null  int64
 16  Education_PhD                 255347 non-null  int64
 17  EmploymentType_Part-time      255347 non-null  int64
 18  EmploymentType_Self-employed  255347 non-null  int64
 19  EmploymentType_Unemployed     255347 non-null  int64
 20  MaritalStatus_Married         255347 non-null  int64
 21  MaritalStatus_Single          255347 non-null  int64
 22  HasMortgage_Yes               255347 non-null  int64
 23  HasDependents_Yes             255347 non-null  int64
 24  LoanPurpose_Business          255347 non-null  int64
 25  LoanPurpose_Education         255347 non-null  int64
 26  LoanPurpose_Home              255347 non-null  int64
 27  LoanPurpose_Other             255347 non-null  int64
 28  HasCoSigner_Yes               255347 non-null  int64
dtypes: float64(5), int64(24)
memory usage: 56.5 MB

In [ ]:
from sklearn.model_selection import train_test_split

# Separate features (X) and target (y)
X = df_encoded.drop(columns=["Default"])
y = df_encoded["Default"]

# Split into training (80%) and test (20%) sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Confirm the split worked and class balance is preserved
print(f"Training set: {X_train.shape[0]} rows")
print(f"Test set: {X_test.shape[0]} rows")
print(f"Training set default rate: {y_train.mean():.4f}")
print(f"Test set default rate: {y_test.mean():.4f}")

Training set: 204277 rows
Test set: 51070 rows
Training set default rate: 0.1161
Test set default rate: 0.1161

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

# Scale numeric features - Logistic Regression performs better when features are on similar scales
numeric_cols = ["Age", "Income", "LoanAmount", "CreditScore", "MonthsEmployed",
                 "NumCreditLines", "InterestRate", "LoanTerm", "DTIRatio", "Loan_to_Income", "Credit_per_Year_Employed"]

scaler = StandardScaler()
X_train_scaled = X_train.copy()
X_test_scaled = X_test.copy()

X_train_scaled[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])
X_test_scaled[numeric_cols] = scaler.transform(X_test[numeric_cols])

# Train Logistic Regression
log_model = LogisticRegression(class_weight="balanced", max_iter=1000, random_state=42)
log_model.fit(X_train_scaled, y_train)

print("Logistic Regression trained successfully")

Logistic Regression trained successfully

In [ ]:
print(f"Logistic Regression - features used: {X_train_scaled.shape[1]}")

Logistic Regression - features used: 28

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

# Logistic Regression predictions
log_preds = log_model.predict(X_test_scaled)
log_probs = log_model.predict_proba(X_test_scaled)[:, 1]

print("=== Logistic Regression ===")
print(classification_report(y_test, log_preds))
print("Confusion Matrix:")
print(confusion_matrix(y_test, log_preds))
print(f"ROC-AUC: {roc_auc_score(y_test, log_probs):.4f}")

=== Logistic Regression ===
              precision    recall  f1-score   support

           0       0.95      0.69      0.80     45139
           1       0.23      0.70      0.34      5931

    accuracy                           0.69     51070
   macro avg       0.59      0.69      0.57     51070
weighted avg       0.86      0.69      0.75     51070

Confusion Matrix:
[[31181 13958]
 [ 1801  4130]]
ROC-AUC: 0.7616

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

params = {'C': [0.01, 0.1, 1, 10, 100]}

grid = GridSearchCV(
    LogisticRegression(class_weight="balanced", max_iter=1000, random_state=42),
    param_grid=params,
    scoring='recall',   # optimizing specifically for catching defaults
    cv=5
)

grid.fit(X_train_scaled, y_train)

print(f"Best C value: {grid.best_params_}")
print(f"Best cross-validated recall: {grid.best_score_:.4f}")

best_log_model = grid.best_estimator_

# Evaluate the tuned model on test set
best_preds = best_log_model.predict(X_test_scaled)
best_probs = best_log_model.predict_proba(X_test_scaled)[:, 1]

print(classification_report(y_test, best_preds))
print(confusion_matrix(y_test, best_preds))
print(f"ROC-AUC: {roc_auc_score(y_test, best_probs):.4f}")

Best C value: {'C': 0.1}
Best cross-validated recall: 0.6861
              precision    recall  f1-score   support

           0       0.95      0.69      0.80     45139
           1       0.23      0.70      0.34      5931

    accuracy                           0.69     51070
   macro avg       0.59      0.69      0.57     51070
weighted avg       0.86      0.69      0.75     51070

[[31173 13966]
 [ 1802  4129]]
ROC-AUC: 0.7616

In [ ]:
import pandas as pd

# Extract coefficients from the trained Logistic Regression model
coefficients = pd.DataFrame({
    "Feature": X_train_scaled.columns,
    "Coefficient": log_model.coef_[0]
})

# Sort by absolute value to see strongest predictors (positive or negative)
coefficients["AbsCoefficient"] = coefficients["Coefficient"].abs()
coefficients = coefficients.sort_values("AbsCoefficient", ascending=False)

print(coefficients.head(15))

                         Feature  Coefficient  AbsCoefficient
0                            Age    -0.574830        0.574830
11                Loan_to_Income     0.473533        0.473533
6                   InterestRate     0.454169        0.454169
18     EmploymentType_Unemployed     0.422852        0.422852
4                 MonthsEmployed    -0.330079        0.330079
16      EmploymentType_Part-time     0.262253        0.262253
27               HasCoSigner_Yes    -0.257624        0.257624
22             HasDependents_Yes    -0.250723        0.250723
17  EmploymentType_Self-employed     0.243764        0.243764
19         MaritalStatus_Married    -0.196514        0.196514
25              LoanPurpose_Home    -0.184402        0.184402
15                 Education_PhD    -0.177778        0.177778
10           Default_Probability     0.173793        0.173793
21               HasMortgage_Yes    -0.157167        0.157167
14            Education_Master's    -0.136859        0.136859

In [ ]:
# Build predictions on the FULL dataset (not just test set) using the chosen model (Logistic Regression)
X_full = df_encoded.drop(columns=["Default"])
X_full_scaled = X_full.copy()
X_full_scaled[numeric_cols] = scaler.transform(X_full[numeric_cols])

df["Predicted_Default"] = log_model.predict(X_full_scaled)
df["Default_Probability"] = log_model.predict_proba(X_full_scaled)[:, 1]

# Export - this keeps LoanID and all original columns, plus the new prediction columns
df.to_csv("loan_predictions.csv", index=False)

print(df[["LoanID", "Default", "Predicted_Default", "Default_Probability"]].head(10))

       LoanID  Default  Predicted_Default  Default_Probability
0  I38PQUQS96        0                  0             0.177738
1  HPSK72WA7R        0                  0             0.138025
2  C1OZ6DPJ8Y        1                  1             0.624594
3  V2KKSFM3UN        0                  1             0.524371
4  EY08JDHTZP        0                  0             0.313029
5  A9S62RQ7US        1                  1             0.781312
6  H8GXPAOS71        0                  0             0.466311
7  0HGZQKJ36W        0                  0             0.130534
8  1R0N3LGNRJ        1                  1             0.585599
9  CM9L1GTT2P        0                  0             0.267896